### ISSUE TITLE
Error in installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by tobiayofe** [ArnoTroch/ONOS-Tutorial#2]
On running the "onos/bin/onos-service start" command, this is the error I encountered:

23:38:35.764 INFO  [FeaturesServiceImpl] Installing bundles:
23:38:35.765 INFO  [FeaturesServiceImpl]   mvn:org.onosproject/onos-core-dist/2.6.0
org.osgi.framework.BundleException: Unable to cache bundle: mvn:org.onosproject/onos-core-dist/2.6.0
        at org.apache.felix.framework.Felix.installBundle(Felix.java:3013)
        at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
        at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundle0(BundleIdBasedRegion.java:117)
        at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundleAtLocation(BundleIdBasedRegion.java:97)
        at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.installBundle(BundleInstallSupportImpl.java:135)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installBundle(FeaturesServiceImpl.java:1138)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:900)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.zip.ZipException: Invalid CEN header (invalid extra data field size for tag: 0xbfef at 5847)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1769)
        at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1274)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1734)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1463)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1426)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:742)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:859)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:257)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:200)
        at org.apache.felix.framework.util.SecureAction.openZipFile(SecureAction.java:650)
        at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:187)
        at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:169)
        at org.apache.felix.framework.util.WeakZipFileFactory.create(WeakZipFileFactory.java:72)
        at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:84)
        at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:872)
        at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550)
        at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153)
        at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277)
        at org.apache.felix.framework.Felix.installBundle(Felix.java:3009)
        ... 12 more
23:38:35.780 ERROR [BootFeaturesInstaller] Error installing boot features
org.osgi.framework.BundleException: Unable to cache bundle: mvn:org.onosproject/onos-core-dist/2.6.0
        at org.apache.felix.framework.Felix.installBundle(Felix.java:3013)
        at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
        at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundle0(BundleIdBasedRegion.java:117)
        at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundleAtLocation(BundleIdBasedRegion.java:97)
        at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.installBundle(BundleInstallSupportImpl.java:135)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installBundle(FeaturesServiceImpl.java:1138)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:900)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.zip.ZipException: Invalid CEN header (invalid extra data field size for tag: 0xbfef at 5847)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1769)
        at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1274)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1734)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1463)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1426)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:742)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:859)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:257)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:200)
        at org.apache.felix.framework.util.SecureAction.openZipFile(SecureAction.java:650)
        at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:187)
        at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:169)
        at org.apache.felix.framework.util.WeakZipFileFactory.create(WeakZipFileFactory.java:72)
        at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:84)
        at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:872)
        at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550)
        at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153)
        at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277)
        at org.apache.felix.framework.Felix.installBundle(Felix.java:3009)
        ... 12 more

![image](https://github.com/ArnoTroch/ONOS-Tutorial/assets/43920326/1b6c52f1-ad65-4184-80fe-fabd9ed233a9)

**Comment by Junaid-Q** [comment]
@ArnoTroch Thanks for the wonderfyl tutorial. Would you please upload some more tutorials related to ONOS REST APIs?

**Comment by ArnoTroch** [comment]
Hi Junaid, I am not planning on making other tutorials on ONOS anytime soon. This was simply a university project that I decided to make publicly available.
