### ISSUE TITLE
Error installing boot features

### ISSUE THREAD

**Issue by ywlaw** [ArnoTroch/ONOS-Tutorial#3]
Hi Arno, thanks so much for providing this tutorial!

I followed this tutorial until this command "sudo /opt/onos/bin/onos-service start" and then encountered the following error (time stamp omitted): 

```
ERROR [BootFeaturesInstaller] Error installing boot features
org.osgi.framework.BundleException: Unable to cache bundle: mvn:org.onosproject/onos-core-dist/2.7.0
        at org.apache.felix.framework.Felix.installBundle(Felix.java:3013)
        at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
        at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundle0(BundleIdBasedRegion.java:117)
        at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundleAtLocation(BundleIdBasedRegion.java:97)
        at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.installBundle(BundleInstallSupportImpl.java:135)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installBundle(FeaturesServiceImpl.java:1138)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:900)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.zip.ZipException: Invalid CEN header (invalid extra data field size for tag: 0xbfef at 5847)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1769)
        at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1274)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1734)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1463)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1426)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:742)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:859)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:257)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:200)
        at org.apache.felix.framework.util.SecureAction.openZipFile(SecureAction.java:650)
        at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:187)
        at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:169)
        at org.apache.felix.framework.util.WeakZipFileFactory.create(WeakZipFileFactory.java:72)
        at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:84)
        at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:872)
        at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550)
        at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153)
        at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277)
        at org.apache.felix.framework.Felix.installBundle(Felix.java:3009)
        ... 12 more
```

The root cause seems to be the lack of verifiability of some signature ("Invalid CEN header"). This error is reproducible on Ubuntu 20.04.6 LTS on WSL2. I haven't found a solution to this yet, but letting you know for the time being.

**Comment by ywlaw** [comment]
Oops, I just found out this issue has been posted before last year, apologies. However, the issue remains unsolved.

**Comment by faniAhmed** [comment]
same issue

**Comment by JordyEGNL** [comment]
same issue here...
```
05:39:47.988 ERROR [BootFeaturesInstaller] Error installing boot features
org.osgi.framework.BundleException: Unable to cache bundle: mvn:org.onosproject/onos-core-dist/2.7.0
        at org.apache.felix.framework.Felix.installBundle(Felix.java:3013)
        at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
        at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundle0(BundleIdBasedRegion.java:117)
        at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundleAtLocation(BundleIdBasedRegion.java:97)
        at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.installBundle(BundleInstallSupportImpl.java:135)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installBundle(FeaturesServiceImpl.java:1138)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:900)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.zip.ZipException: Invalid CEN header (invalid extra data field size for tag: 0xbfef at 5847)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1776)
        at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1275)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1741)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1470)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1433)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:743)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:860)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:258)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:187)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:201)
        at org.apache.felix.framework.util.SecureAction.openZipFile(SecureAction.java:650)
        at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:187)
        at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:169)
        at org.apache.felix.framework.util.WeakZipFileFactory.create(WeakZipFileFactory.java:72)
        at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:84)
        at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:872)
        at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550)
        at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153)
        at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277)
        at org.apache.felix.framework.Felix.installBundle(Felix.java:3009)
        ... 12 more
```

**Comment by ArnoTroch** [comment]
Hi all

My apologies for the (very) late response. Since I had some free time on my hands, I tried to reproduce this problem. I managed to circumvent the error message by adding the argument `-Djdk.util.zip.disableZip64ExtraFieldValidation=true` to the `JAVA_OPTS` in the `/opt/onos/bin/onos-service` file. This seems to disable some validations and allowed me to run the ONOS service successfully.  

Hope this helps despite the late reply!

**Comment by Cheeyan902** [comment]
@JordyEGNL @ArnoTroch May i know where you add the argument -Djdk.util in onos-service file? Since there is two section for JAVA_OPTS in the file and I added it at the first line of JAVA_OPTS but still face the same problem.

**Comment by Cheeyan902** [comment]
@ArnoTroch I had added -Djdk.util argument in the first line of JAVA_OPTS but error occured when I try to access the CLI. Showing the onos is not running. 

![Image](https://github.com/user-attachments/assets/775c71a7-4edd-46d7-9476-aaee3e63f005)
